# 
# This workflow will execute a Javadoc-related command using Maven
#
name: Javadoc

on:
  workflow_call:
    inputs:
        maven-command:
          required: true
          type: string    
    secrets:
      SONAR_TOKEN:
        required: true        

jobs:
    
  javadoc:
    uses: ./.github/workflows/_maven.yml
    with:
      maven-command: clean install
      maven-command-extra: javadoc:javadoc
      os: ubuntu-latest
      java-version: 8
    secrets: inherit    

