# 
# This workflow will scan and publish a python project to sonarcloud
#
name: Publish to sonarcloud

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      MAVEN_USERNAME:
        required: true 
      MAVEN_PASSWORD:
        required: true        
      GPG_SIGNING_KEY:
        required: true 
      GPG_PASSPHRASE:
        required: true

jobs:
        
  sonarcloud:
    uses: ./.github/workflows/_maven.yml
    with:
      maven-command: verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      os: ubuntu-latest
      java-version: 21
      cache-sonar: true
    secrets: inherit    
