# 
# This workflow will run tests using maven
#
name: Test using maven

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      java-version:
        required: true
        type: string
      upload-artifact:
        required: false
        type: string         
    secrets:
      SONAR_TOKEN:
        required: true
      MAVEN_USERNAME:
        required: true 
      MAVEN_PASSWORD:
        required: true        
      GPG_SIGNING_KEY:
        required: true 
      GPG_PASSPHRASE:
        required: true        

jobs:

  test:
    uses: ./.github/workflows/_maven.yml
    with:
      maven-command: verify
      os: ${{ inputs.os }}
      java-version: ${{ inputs.java-version }}
      upload-artifact: ${{ inputs.upload-artifact }}
      publish-test-report: true
    secrets: inherit    
