# 
# This workflow will run tests using maven
#
name: Test using maven for ${{ inputs.os }}-jdk${{ inputs.java-version }}:

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      java-version:
        required: true
        type: string                  
    secrets:
      SONAR_TOKEN:
        required: true        

jobs:

  test-${{ inputs.os }}-jdk${{ inputs.java-version }}:

    runs-on: ${{ inputs.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ inputs.java-version }}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-jdk${{ inputs.java-version }}
        restore-keys: ${{ runner.os }}-m2
    - name: Create settings.xml for Maven
      uses: s4u/maven-settings-action@v2.2.0
      with:
        servers: |
            [{
                "id": "path-pattern-finder",
                "username": "$GITHUB_ACTOR",
                "password": "${{ secrets.GITHUB_TOKEN }}"
            }]    
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -DtestFailureIgnore --batch-mode --update-snapshots verify
    - name: Publish Test Report
      uses: scacap/action-surefire-report@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_test_failures: true
        fail_if_no_tests: false
        check_name: Test Report - ${{ inputs.os }}-jdk${{ inputs.java-version }}
