# 
# Push request triggered by a push to dev branch.
#
# This workflow will:
#  - run unit tests
#  - generate javadocs to check for errors (but doesn't publish them).
#  - submit project state to Sonarccloud.submit to Sonarcloud.
#

name: python_ci_push_dev

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true 
       MAVEN_USERNAME:
         required: true 
       MAVEN_PASSWORD:
         required: true        
       GPG_SIGNING_KEY:
         required: true 
       GPG_PASSPHRASE:
         required: true

jobs:
  test:
    uses: ./.github/workflows/_test.yml
   
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [21,24]

    with:
      os: ${{ matrix.os }}
      java-version: ${{ matrix.java }}

    secrets: inherit

  javadoc:
    uses: ./.github/workflows/_clean_maven.yml
    with:
      maven-command: deploy javadoc:javadoc
    secrets: inherit    
        
  # Disabled as the scanner requires at least Java 11
  sonarcloud:
   uses: ./.github/workflows/_sonarcloud.yml
   secrets: inherit    
