# 
# Push request triggered by a push to dev branch.
#
# This workflow will:
#  - run unit tests
#  - submit project state to Sonarccloud.submit to Sonarcloud.
#
#

name: python_ci_push_master

on:
  workflow_call:
    inputs:
        # Whether to upload artifiacts from the 
        upload-artifact:
          required: false
          type: string    
    secrets:
      SONAR_TOKEN:
        required: true
      MAVEN_USERNAME:
        required: true 
      MAVEN_PASSWORD:
        required: true        
      GPG_SIGNING_KEY:
        required: true 
      GPG_PASSPHRASE:
        required: true        

jobs:

  deploy_and_javadoc:
      uses: ./.github/workflows/_clean_maven.yml
      with:
        maven-command: javadoc:jar source:jar verify
        upload-artifact: ${{ inputs.upload-artifact }}
      secrets: inherit
    
      
  # Disabled as the scanner requires at least Java 11
  sonarcloud:
    uses: ./.github/workflows/_sonarcloud.yml
    secrets: inherit    
