# 
# Push request triggered by a push to dev branch.
#
# This workflow will:
#  - run unit tests
#  - submit project state to Sonarccloud.submit to Sonarcloud.
#
#

name: python_ci_push_master

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true        


jobs:

  deploy_and_javadoc:
      uses: ./.github/workflows/_clean_maven.yml
      with:
        maven-command: javadoc:jar source:jar deploy
      secrets: inherit
    
      
  sonarcloud:
    uses: ./.github/workflows/_sonarcloud.yml
    secrets: inherit    
