# 
# Push request triggered by a push to dev branch.
#
# This workflow will:
#  - run unit tests
#  - submit project state to Sonarccloud.submit to Sonarccloud.
#
#

name: python_ci_push_dev

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true        


jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [8, 11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-jdk${{ matrix.java }}
        restore-keys: ${{ runner.os }}-m2
    - name: Create settings.xml for Maven
      uses: s4u/maven-settings-action@v2.2.0
      with:
        servers: |
            [{
                "id": "path-pattern-finder",
                "username": "$GITHUB_ACTOR",
                "password": "${{ secrets.GITHUB_TOKEN }}"
            }]    
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -DtestFailureIgnore --batch-mode --update-snapshots verify
    - name: Publish Test Report
      uses: scacap/action-surefire-report@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        fail_on_test_failures: true
        fail_if_no_tests: false
        check_name: Test Report - ${{ matrix.os }}-jdk${{ matrix.java }}

        
  sonarcloud:
    uses: ./.github/workflows/_sonarcloud.yml
    with:
      runner-os: ${{ runner.os }}
    secrets: inherit

    
  javadoc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}-jdk8
        restore-keys: ${{ runner.os }}-m2
    - name: Create settings.xml for Maven
      uses: s4u/maven-settings-action@v2.2.0
      with:
        servers: |
            [{
                "id": "path-pattern-finder",
                "username": "$GITHUB_ACTOR",
                "password": "${{ secrets.GITHUB_TOKEN }}"
            }]    
    - name: Compile before running Javadoc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn --batch-mode --update-snapshots clean install            
    - name: Generate Javadoc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn --batch-mode javadoc:javadoc
